// lib/datos.dart

final Map<String, List<Map<String, String>>> categorias = {
  'Animales': [
    {'palabra': 'Perro', 'pista': 'Mascota', 'palabra_en': 'Dog', 'pista_en': 'Pet'},
    {'palabra': 'Gato', 'pista': 'Mascota', 'palabra_en': 'Cat', 'pista_en': 'Pet'},
    {'palabra': 'Elefante', 'pista': 'Mamífero', 'palabra_en': 'Elephant', 'pista_en': 'Mammal'},
    {'palabra': 'Delfín', 'pista': 'Inteligente', 'palabra_en': 'Dolphin', 'pista_en': 'Intelligent'},
    {'palabra': 'León', 'pista': 'Depredador', 'palabra_en': 'Lion', 'pista_en': 'Predator'},
    {'palabra': 'Tiburón', 'pista': 'Depredador', 'palabra_en': 'Shark', 'pista_en': 'Predator'},
    {'palabra': 'Pingüino', 'pista': 'Antártida', 'palabra_en': 'Penguin', 'pista_en': 'Antarctica'},
    {'palabra': 'Serpiente', 'pista': 'Reptil', 'palabra_en': 'Snake', 'pista_en': 'Reptile'},
    {'palabra': 'Jirafa', 'pista': 'Altura', 'palabra_en': 'Giraffe', 'pista_en': 'Height'},
    {'palabra': 'Vaca', 'pista': 'Granja', 'palabra_en': 'Cow', 'pista_en': 'Farm'},
    {'palabra': 'Canguro', 'pista': 'Salto', 'palabra_en': 'Kangaroo', 'pista_en': 'Jump'},
    {'palabra': 'Águila', 'pista': 'Vuelo', 'palabra_en': 'Eagle', 'pista_en': 'Flight'},
    {'palabra': 'Cocodrilo', 'pista': 'Río', 'palabra_en': 'Crocodile', 'pista_en': 'River'},
    {'palabra': 'Oso Polar', 'pista': 'Frío', 'palabra_en': 'Polar Bear', 'pista_en': 'Cold'},
    {'palabra': 'Hámster', 'pista': 'Jaula', 'palabra_en': 'Hamster', 'pista_en': 'Cage'},
    {'palabra': 'Lobo', 'pista': 'Manada', 'palabra_en': 'Wolf', 'pista_en': 'Pack'},
    {'palabra': 'Cebra', 'pista': 'Rayas', 'palabra_en': 'Zebra', 'pista_en': 'Stripes'},
    {'palabra': 'Gorila', 'pista': 'Primate', 'palabra_en': 'Gorilla', 'pista_en': 'Primate'},
    {'palabra': 'Pulpo', 'pista': 'Mar', 'palabra_en': 'Octopus', 'pista_en': 'Sea'},
    {'palabra': 'Murciélago', 'pista': 'Cueva', 'palabra_en': 'Bat', 'pista_en': 'Cave'},
    {'palabra': 'Hipopótamo', 'pista': 'Pesado', 'palabra_en': 'Hippopotamus', 'pista_en': 'Heavy'},
    {'palabra': 'Camaleón', 'pista': 'Color', 'palabra_en': 'Chameleon', 'pista_en': 'Color'},
  ],
  'Comidas': [
    {'palabra': 'Paella', 'pista': 'Arroz', 'palabra_en': 'Paella', 'pista_en': 'Rice'},
    {'palabra': 'Tortilla', 'pista': 'Huevos', 'palabra_en': 'Omelette', 'pista_en': 'Eggs'},
    {'palabra': 'Pizza', 'pista': 'Italia', 'palabra_en': 'Pizza', 'pista_en': 'Italy'},
    {'palabra': 'Hamburguesa', 'pista': 'Carne', 'palabra_en': 'Burger', 'pista_en': 'Meat'},
    {'palabra': 'Croquetas', 'pista': 'Fritura', 'palabra_en': 'Croquettes', 'pista_en': 'Fried'},
    {'palabra': 'Sushi', 'pista': 'Pescado', 'palabra_en': 'Sushi', 'pista_en': 'Fish'},
    {'palabra': 'Lentejas', 'pista': 'Cuchara', 'palabra_en': 'Lentils', 'pista_en': 'Spoon'},
    {'palabra': 'Gazpacho', 'pista': 'Tomate', 'palabra_en': 'Gazpacho', 'pista_en': 'Tomato'},
    {'palabra': 'Pasta', 'pista': 'Trigo', 'palabra_en': 'Pasta', 'pista_en': 'Wheat'},
    {'palabra': 'Churros', 'pista': 'Masa frita', 'palabra_en': 'Churros', 'pista_en': 'Fried dough'},
    {'palabra': 'Tacos', 'pista': 'México', 'palabra_en': 'Tacos', 'pista_en': 'Mexico'},
    {'palabra': 'Ramen', 'pista': 'Sopa', 'palabra_en': 'Ramen', 'pista_en': 'Soup'},
    {'palabra': 'Lasaña', 'pista': 'Capas', 'palabra_en': 'Lasagna', 'pista_en': 'Layers'},
    {'palabra': 'Ceviche', 'pista': 'Marinado', 'palabra_en': 'Ceviche', 'pista_en': 'Marinated'},
    {'palabra': 'Kebab', 'pista': 'Carne enrollada', 'palabra_en': 'Kebab', 'pista_en': 'Rolled meat'},
    {'palabra': 'Helado', 'pista': 'Postre frío', 'palabra_en': 'Ice Cream', 'pista_en': 'Cold dessert'},
    {'palabra': 'Tarta de Queso', 'pista': 'Dulce', 'palabra_en': 'Cheesecake', 'pista_en': 'Sweet'},
    {'palabra': 'Ensalada', 'pista': 'Vegetales', 'palabra_en': 'Salad', 'pista_en': 'Vegetables'},
    {'palabra': 'Filete', 'pista': 'Plancha', 'palabra_en': 'Steak', 'pista_en': 'Grilled'},
    {'palabra': 'Hot Dog', 'pista': 'Salchicha', 'palabra_en': 'Hot Dog', 'pista_en': 'Sausage'},
    {'palabra': 'Burrito', 'pista': 'Tortilla rellena', 'palabra_en': 'Burrito', 'pista_en': 'Stuffed tortilla'},
  ],
  'Objetos': [
    {'palabra': 'Móvil', 'pista': 'Pantalla', 'palabra_en': 'Phone', 'pista_en': 'Screen'},
    {'palabra': 'Ordenador', 'pista': 'Teclado', 'palabra_en': 'Computer', 'pista_en': 'Keyboard'},
    {'palabra': 'Bicicleta', 'pista': 'Pedales', 'palabra_en': 'Bicycle', 'pista_en': 'Pedals'},
    {'palabra': 'Gafas', 'pista': 'Visión', 'palabra_en': 'Glasses', 'pista_en': 'Vision'},
    {'palabra': 'Reloj', 'pista': 'Muñeca', 'palabra_en': 'Watch', 'pista_en': 'Wrist'},
    {'palabra': 'Mochila', 'pista': 'Espalda', 'palabra_en': 'Backpack', 'pista_en': 'Back'},
    {'palabra': 'Cama', 'pista': 'Dormir', 'palabra_en': 'Bed', 'pista_en': 'Sleep'},
    {'palabra': 'Espejo', 'pista': 'Reflejo', 'palabra_en': 'Mirror', 'pista_en': 'Reflection'},
    {'palabra': 'Paraguas', 'pista': 'Agua', 'palabra_en': 'Umbrella', 'pista_en': 'Water'},
    {'palabra': 'Coche', 'pista': 'Ruedas', 'palabra_en': 'Car', 'pista_en': 'Wheels'},
    {'palabra': 'Cámara', 'pista': 'Fotos', 'palabra_en': 'Camera', 'pista_en': 'Photos'},
    {'palabra': 'Libro', 'pista': 'Lectura', 'palabra_en': 'Book', 'pista_en': 'Reading'},
    {'palabra': 'Llaves', 'pista': 'Puerta', 'palabra_en': 'Keys', 'pista_en': 'Door'},
    {'palabra': 'Martillo', 'pista': 'Herramienta', 'palabra_en': 'Hammer', 'pista_en': 'Tool'},
    {'palabra': 'Guitarra', 'pista': 'Cuerdas', 'palabra_en': 'Guitar', 'pista_en': 'Strings'},
    {'palabra': 'Silla', 'pista': 'Asiento', 'palabra_en': 'Chair', 'pista_en': 'Seat'},
    {'palabra': 'Botella', 'pista': 'Líquido', 'palabra_en': 'Bottle', 'pista_en': 'Liquid'},
    {'palabra': 'Cartera', 'pista': 'Dinero', 'palabra_en': 'Wallet', 'pista_en': 'Money'},
    {'palabra': 'Auriculares', 'pista': 'Sonido', 'palabra_en': 'Headphones', 'pista_en': 'Sound'},
    {'palabra': 'Linterna', 'pista': 'Luz', 'palabra_en': 'Flashlight', 'pista_en': 'Light'},
  ],
  'Lugares': [
    {'palabra': 'Madrid', 'pista': 'España', 'palabra_en': 'Madrid', 'pista_en': 'Spain'},
    {'palabra': 'París', 'pista': 'Francia', 'palabra_en': 'Paris', 'pista_en': 'France'},
    {'palabra': 'La Playa', 'pista': 'Arena', 'palabra_en': 'The Beach', 'pista_en': 'Sand'},
    {'palabra': 'El Colegio', 'pista': 'Libros', 'palabra_en': 'School', 'pista_en': 'Books'},
    {'palabra': 'Nueva York', 'pista': 'EE.UU.', 'palabra_en': 'New York', 'pista_en': 'USA'},
    {'palabra': 'Gimnasio', 'pista': 'Pesas', 'palabra_en': 'Gym', 'pista_en': 'Weights'},
    {'palabra': 'Cine', 'pista': 'Palomitas', 'palabra_en': 'Cinema', 'pista_en': 'Popcorn'},
    {'palabra': 'Hospital', 'pista': 'Médicos', 'palabra_en': 'Hospital', 'pista_en': 'Doctors'},
    {'palabra': 'Aeropuerto', 'pista': 'Aviones', 'palabra_en': 'Airport', 'pista_en': 'Planes'},
    {'palabra': 'Supermercado', 'pista': 'Comida', 'palabra_en': 'Supermarket', 'pista_en': 'Food'},
    {'palabra': 'Biblioteca', 'pista': 'Silencio', 'palabra_en': 'Library', 'pista_en': 'Silence'},
    {'palabra': 'Estadio', 'pista': 'Gradas', 'palabra_en': 'Stadium', 'pista_en': 'Bleachers'},
    {'palabra': 'Bosque', 'pista': 'Árboles', 'palabra_en': 'Forest', 'pista_en': 'Trees'},
    {'palabra': 'Desierto', 'pista': 'Calor', 'palabra_en': 'Desert', 'pista_en': 'Heat'},
    {'palabra': 'Museo', 'pista': 'Cuadros', 'palabra_en': 'Museum', 'pista_en': 'Paintings'},
    {'palabra': 'Montaña', 'pista': 'Cumbre', 'palabra_en': 'Mountain', 'pista_en': 'Summit'},
    {'palabra': 'Iglesia', 'pista': 'Religión', 'palabra_en': 'Church', 'pista_en': 'Religion'},
    {'palabra': 'Farmacia', 'pista': 'Medicinas', 'palabra_en': 'Pharmacy', 'pista_en': 'Medicines'},
    {'palabra': 'Zoológico', 'pista': 'Jaulas', 'palabra_en': 'Zoo', 'pista_en': 'Cages'},
    {'palabra': 'Puerto', 'pista': 'Barcos', 'palabra_en': 'Port', 'pista_en': 'Ships'},
  ],
  'Cine y TV': [
    {'palabra': 'Star Wars', 'pista': 'Galaxia', 'palabra_en': 'Star Wars', 'pista_en': 'Galaxy'},
    {'palabra': 'Harry Potter', 'pista': 'Varita', 'palabra_en': 'Harry Potter', 'pista_en': 'Wand'},
    {'palabra': 'Titanic', 'pista': 'Barco', 'palabra_en': 'Titanic', 'pista_en': 'Ship'},
    {'palabra': 'Los Simpson', 'pista': 'Amarillos', 'palabra_en': 'The Simpsons', 'pista_en': 'Yellow'},
    {'palabra': 'La Casa de Papel', 'pista': 'Máscara', 'palabra_en': 'Money Heist', 'pista_en': 'Mask'},
    {'palabra': 'Batman', 'pista': 'Murciélago', 'palabra_en': 'Batman', 'pista_en': 'Bat'},
    {'palabra': 'Jurassic Park', 'pista': 'Isla', 'palabra_en': 'Jurassic Park', 'pista_en': 'Island'},
    {'palabra': 'Toy Story', 'pista': 'Juguetes', 'palabra_en': 'Toy Story', 'pista_en': 'Toys'},
    {'palabra': 'Avatar', 'pista': 'Azules', 'palabra_en': 'Avatar', 'pista_en': 'Blue'},
    {'palabra': 'El Rey León', 'pista': 'Selva', 'palabra_en': 'The Lion King', 'pista_en': 'Jungle'},
    {'palabra': 'Avengers', 'pista': 'Héroes', 'palabra_en': 'Avengers', 'pista_en': 'Heroes'},
    {'palabra': 'Stranger Things', 'pista': 'Ochenta', 'palabra_en': 'Stranger Things', 'pista_en': 'Eighties'},
    {'palabra': 'Juego de Tronos', 'pista': 'Dragones', 'palabra_en': 'Game of Thrones', 'pista_en': 'Dragons'},
    {'palabra': 'Spiderman', 'pista': 'Araña', 'palabra_en': 'Spiderman', 'pista_en': 'Spider'},
    {'palabra': 'Shrek', 'pista': 'Ogro', 'palabra_en': 'Shrek', 'pista_en': 'Ogre'},
    {'palabra': 'El Padrino', 'pista': 'Mafia', 'palabra_en': 'The Godfather', 'pista_en': 'Mafia'},
    {'palabra': 'Matrix', 'pista': 'Simulación', 'palabra_en': 'Matrix', 'pista_en': 'Simulation'},
    {'palabra': 'Gladiator', 'pista': 'Roma', 'palabra_en': 'Gladiator', 'pista_en': 'Rome'},
    {'palabra': 'Piratas del Caribe', 'pista': 'Tesoro', 'palabra_en': 'Pirates of the Caribbean', 'pista_en': 'Treasure'},
    {'palabra': 'Squid Game', 'pista': 'Corea', 'palabra_en': 'Squid Game', 'pista_en': 'Korea'},
  ],
  'Deportes': [
    {'palabra': 'Fútbol', 'pista': 'Goles', 'palabra_en': 'Soccer', 'pista_en': 'Goals'},
    {'palabra': 'Baloncesto', 'pista': 'Canasta', 'palabra_en': 'Basketball', 'pista_en': 'Hoop'},
    {'palabra': 'Tenis', 'pista': 'Pista', 'palabra_en': 'Tennis', 'pista_en': 'Court'},
    {'palabra': 'Natación', 'pista': 'Piscina', 'palabra_en': 'Swimming', 'pista_en': 'Pool'},
    {'palabra': 'Ciclismo', 'pista': 'Carretera', 'palabra_en': 'Cycling', 'pista_en': 'Road'},
    {'palabra': 'Boxeo', 'pista': 'Guantes', 'palabra_en': 'Boxing', 'pista_en': 'Gloves'},
    {'palabra': 'Golf', 'pista': 'Hoyo', 'palabra_en': 'Golf', 'pista_en': 'Hole'},
    {'palabra': 'Esquí', 'pista': 'Montaña', 'palabra_en': 'Skiing', 'pista_en': 'Mountain'},
    {'palabra': 'Yoga', 'pista': 'Esterilla', 'palabra_en': 'Yoga', 'pista_en': 'Mat'},
    {'palabra': 'Voleibol', 'pista': 'Salto', 'palabra_en': 'Volleyball', 'pista_en': 'Jump'},
    {'palabra': 'Rugby', 'pista': 'Melé', 'palabra_en': 'Rugby', 'pista_en': 'Scrum'},
    {'palabra': 'Pádel', 'pista': 'Pala', 'palabra_en': 'Padel', 'pista_en': 'Paddle'},
    {'palabra': 'Surf', 'pista': 'Olas', 'palabra_en': 'Surfing', 'pista_en': 'Waves'},
    {'palabra': 'Atletismo', 'pista': 'Carrera', 'palabra_en': 'Athletics', 'pista_en': 'Race'},
    {'palabra': 'Ping Pong', 'pista': 'Mesa', 'palabra_en': 'Ping Pong', 'pista_en': 'Table'},
    {'palabra': 'Bádminton', 'pista': 'Volante', 'palabra_en': 'Badminton', 'pista_en': 'Shuttlecock'},
    {'palabra': 'Kárate', 'pista': 'Cinturón', 'palabra_en': 'Karate', 'pista_en': 'Belt'},
    {'palabra': 'Balonmano', 'pista': 'Portería', 'palabra_en': 'Handball', 'pista_en': 'Goal'},
    {'palabra': 'Fórmula 1', 'pista': 'Velocidad', 'palabra_en': 'Formula 1', 'pista_en': 'Speed'},
    {'palabra': 'Patinaje', 'pista': 'Cuchilla', 'palabra_en': 'Skating', 'pista_en': 'Blade'},
  ],
  'Profesiones': [
    {'palabra': 'Médico', 'pista': 'Bata', 'palabra_en': 'Doctor', 'pista_en': 'Lab coat'},
    {'palabra': 'Bombero', 'pista': 'Fuego', 'palabra_en': 'Firefighter', 'pista_en': 'Fire'},
    {'palabra': 'Policía', 'pista': 'Sirena', 'palabra_en': 'Police', 'pista_en': 'Siren'},
    {'palabra': 'Profesor', 'pista': 'Pizarra', 'palabra_en': 'Teacher', 'pista_en': 'Whiteboard'},
    {'palabra': 'Astronauta', 'pista': 'Cohete', 'palabra_en': 'Astronaut', 'pista_en': 'Rocket'},
    {'palabra': 'Mecánico', 'pista': 'Aceite', 'palabra_en': 'Mechanic', 'pista_en': 'Oil'},
    {'palabra': 'Peluquero', 'pista': 'Tijeras', 'palabra_en': 'Hairdresser', 'pista_en': 'Scissors'},
    {'palabra': 'Cocinero', 'pista': 'Sartén', 'palabra_en': 'Cook', 'pista_en': 'Pan'},
    {'palabra': 'Pintor', 'pista': 'Pincel', 'palabra_en': 'Painter', 'pista_en': 'Brush'},
    {'palabra': 'Cantante', 'pista': 'Micro', 'palabra_en': 'Singer', 'pista_en': 'Mic'},
    {'palabra': 'Arquitecto', 'pista': 'Planos', 'palabra_en': 'Architect', 'pista_en': 'Blueprints'},
    {'palabra': 'Abogado', 'pista': 'Juicio', 'palabra_en': 'Lawyer', 'pista_en': 'Trial'},
    {'palabra': 'Carpintero', 'pista': 'Madera', 'palabra_en': 'Carpenter', 'pista_en': 'Wood'},
    {'palabra': 'Dentista', 'pista': 'Dientes', 'palabra_en': 'Dentist', 'pista_en': 'Teeth'},
    {'palabra': 'Periodista', 'pista': 'Noticias', 'palabra_en': 'Journalist', 'pista_en': 'News'},
    {'palabra': 'Agricultor', 'pista': 'Campo', 'palabra_en': 'Farmer', 'pista_en': 'Field'},
    {'palabra': 'Electricista', 'pista': 'Cables', 'palabra_en': 'Electrician', 'pista_en': 'Cables'},
    {'palabra': 'Vendedor', 'pista': 'Tienda', 'palabra_en': 'Seller', 'pista_en': 'Shop'},
    {'palabra': 'Veterinario', 'pista': 'Animales', 'palabra_en': 'Vet', 'pista_en': 'Animals'},
    {'palabra': 'Bailarín', 'pista': 'Escenario', 'palabra_en': 'Dancer', 'pista_en': 'Stage'},
  ],
  'Videojuegos': [
    {'palabra': 'Super Mario', 'pista': 'Fontanero', 'palabra_en': 'Super Mario', 'pista_en': 'Plumber'},
    {'palabra': 'Minecraft', 'pista': 'Cubos', 'palabra_en': 'Minecraft', 'pista_en': 'Blocks'},
    {'palabra': 'Fortnite', 'pista': 'Baile', 'palabra_en': 'Fortnite', 'pista_en': 'Dance'},
    {'palabra': 'FIFA', 'pista': 'Césped', 'palabra_en': 'FIFA', 'pista_en': 'Grass'},
    {'palabra': 'Pokémon', 'pista': 'Bola', 'palabra_en': 'Pokémon', 'pista_en': 'Ball'},
    {'palabra': 'Zelda', 'pista': 'Espada', 'palabra_en': 'Zelda', 'pista_en': 'Sword'},
    {'palabra': 'Tetris', 'pista': 'Piezas', 'palabra_en': 'Tetris', 'pista_en': 'Pieces'},
    {'palabra': 'Among Us', 'pista': 'Traidor', 'palabra_en': 'Among Us', 'pista_en': 'Traitor'},
    {'palabra': 'Pac-Man', 'pista': 'Fantasmas', 'palabra_en': 'Pac-Man', 'pista_en': 'Ghosts'},
    {'palabra': 'GTA', 'pista': 'Crimen', 'palabra_en': 'GTA', 'pista_en': 'Crime'},
    {'palabra': 'League of Legends', 'pista': 'PC', 'palabra_en': 'League of Legends', 'pista_en': 'PC'},
    {'palabra': 'Sonic', 'pista': 'Veloz', 'palabra_en': 'Sonic', 'pista_en': 'Fast'},
    {'palabra': 'Call of Duty', 'pista': 'Guerra', 'palabra_en': 'Call of Duty', 'pista_en': 'War'},
    {'palabra': 'God of War', 'pista': 'Mitología', 'palabra_en': 'God of War', 'pista_en': 'Mythology'},
    {'palabra': 'Final Fantasy', 'pista': 'Rol', 'palabra_en': 'Final Fantasy', 'pista_en': 'RPG'},
    {'palabra': 'The Sims', 'pista': 'Vida', 'palabra_en': 'The Sims', 'pista_en': 'Life'},
    {'palabra': 'Resident Evil', 'pista': 'Miedo', 'palabra_en': 'Resident Evil', 'pista_en': 'Fear'},
    {'palabra': 'Halo', 'pista': 'Casco', 'palabra_en': 'Halo', 'pista_en': 'Helmet'},
    {'palabra': 'Animal Crossing', 'pista': 'Pueblo', 'palabra_en': 'Animal Crossing', 'pista_en': 'Village'},
    {'palabra': 'Roblox', 'pista': 'Plataforma', 'palabra_en': 'Roblox', 'pista_en': 'Platform'},
  ],
  'Personajes Famosos': [
    {'palabra': 'Rafa Nadal', 'pista': 'Tenista', 'palabra_en': 'Rafa Nadal', 'pista_en': 'Tennis player'},
    {'palabra': 'Messi', 'pista': 'Fútbol', 'palabra_en': 'Messi', 'pista_en': 'Soccer'},
    {'palabra': 'Rosalía', 'pista': 'Motomami', 'palabra_en': 'Rosalía', 'pista_en': 'Motomami'},
    {'palabra': 'Ibai Llanos', 'pista': 'Streamer', 'palabra_en': 'Ibai Llanos', 'pista_en': 'Streamer'},
    {'palabra': 'Spider-Man', 'pista': 'Peter Parker', 'palabra_en': 'Spider-Man', 'pista_en': 'Peter Parker'},
    {'palabra': 'Mickey Mouse', 'pista': 'Disney', 'palabra_en': 'Mickey Mouse', 'pista_en': 'Disney'},
    {'palabra': 'Sherlock Holmes', 'pista': 'Lupa', 'palabra_en': 'Sherlock Holmes', 'pista_en': 'Magnifying glass'},
    {'palabra': 'Don Quijote', 'pista': 'Molinos', 'palabra_en': 'Don Quixote', 'pista_en': 'Windmills'},
    {'palabra': 'Cristiano Ronaldo', 'pista': 'Portugal', 'palabra_en': 'Cristiano Ronaldo', 'pista_en': 'Portugal'},
    {'palabra': 'Donald Trump', 'pista': 'EE.UU.', 'palabra_en': 'Donald Trump', 'pista_en': 'USA'},
    {'palabra': 'Albert Einstein', 'pista': 'Genio', 'palabra_en': 'Albert Einstein', 'pista_en': 'Genius'},
    {'palabra': 'Michael Jordan', 'pista': 'Basket', 'palabra_en': 'Michael Jordan', 'pista_en': 'Basket'},
    {'palabra': 'Elon Musk', 'pista': 'Espacio', 'palabra_en': 'Elon Musk', 'pista_en': 'Space'},
    {'palabra': 'Elvis Presley', 'pista': 'Rock', 'palabra_en': 'Elvis Presley', 'pista_en': 'Rock'},
    {'palabra': 'Marilyn Monroe', 'pista': 'Rubia', 'palabra_en': 'Marilyn Monroe', 'pista_en': 'Blonde'},
    {'palabra': 'Steve Jobs', 'pista': 'Manzana', 'palabra_en': 'Steve Jobs', 'pista_en': 'Apple'},
    {'palabra': 'Beyoncé', 'pista': 'Diva', 'palabra_en': 'Beyoncé', 'pista_en': 'Diva'},
    {'palabra': 'Lady Gaga', 'pista': 'Pop', 'palabra_en': 'Lady Gaga', 'pista_en': 'Pop'},
    {'palabra': 'Freddie Mercury', 'pista': 'Bigote', 'palabra_en': 'Freddie Mercury', 'pista_en': 'Mustache'},
    {'palabra': 'Picasso', 'pista': 'Cuadros', 'palabra_en': 'Picasso', 'pista_en': 'Paintings'},
  ],
  'Cosas de Casa': [
    {'palabra': 'Frigorífico', 'pista': 'Cocina', 'palabra_en': 'Fridge', 'pista_en': 'Kitchen'},
    {'palabra': 'Microondas', 'pista': 'Cocina', 'palabra_en': 'Microwave', 'pista_en': 'Kitchen'},
    {'palabra': 'Lavadora', 'pista': 'Ropa', 'palabra_en': 'Washing machine', 'pista_en': 'Clothes'},
    {'palabra': 'Sofá', 'pista': 'Cojines', 'palabra_en': 'Sofa', 'pista_en': 'Cushions'},
    {'palabra': 'Televisión', 'pista': 'Mando', 'palabra_en': 'Television', 'pista_en': 'Remote'},
    {'palabra': 'Ducha', 'pista': 'Jabón', 'palabra_en': 'Shower', 'pista_en': 'Soap'},
    {'palabra': 'Cama', 'pista': 'Sábanas', 'palabra_en': 'Bed', 'pista_en': 'Sheets'},
    {'palabra': 'Escoba', 'pista': 'Suelo', 'palabra_en': 'Broom', 'pista_en': 'Floor'},
    {'palabra': 'Lámpara', 'pista': 'Bombilla', 'palabra_en': 'Lamp', 'pista_en': 'Lightbulb'},
    {'palabra': 'Espejo', 'pista': 'Baño', 'palabra_en': 'Mirror', 'pista_en': 'Bathroom'},
    {'palabra': 'Plancha', 'pista': 'Calor', 'palabra_en': 'Iron', 'pista_en': 'Heat'},
    {'palabra': 'Tostadora', 'pista': 'Pan', 'palabra_en': 'Toaster', 'pista_en': 'Bread'},
    {'palabra': 'Alfombra', 'pista': 'Suelo', 'palabra_en': 'Rug', 'pista_en': 'Floor'},
    {'palabra': 'Cortina', 'pista': 'Ventana', 'palabra_en': 'Curtain', 'pista_en': 'Window'},
    {'palabra': 'Mesita de noche', 'pista': 'Cerca', 'palabra_en': 'Nightstand', 'pista_en': 'Close by'},
    {'palabra': 'Almohada', 'pista': 'Cabeza', 'palabra_en': '枕', 'pista_en': 'Head'},
    {'palabra': 'Toalla', 'pista': 'Secar', 'palabra_en': 'Towels', 'pista_en': 'Dry'},
    {'palabra': 'Cubertería', 'pista': 'Metal', 'palabra_en': 'Cutlery', 'pista_en': 'Metal'},
    {'palabra': 'Sartén', 'pista': 'Fuego', 'palabra_en': 'Pan', 'pista_en': 'Fire'},
    {'palabra': 'Armario', 'pista': 'Perchas', 'palabra_en': 'Wardrobe', 'pista_en': 'Hangers'},
  ],
  'Adultos': [
    {'palabra': 'Vibrador', 'pista': 'Pilas', 'palabra_en': 'Vibrator', 'pista_en': 'Batteries'},
    {'palabra': 'Lencería', 'pista': 'Encaje', 'palabra_en': 'Lingerie', 'pista_en': 'Lace'},
    {'palabra': 'Kamasutra', 'pista': 'Dibujos', 'palabra_en': 'Kamasutra', 'pista_en': 'Drawings'},
    {'palabra': 'Esposas', 'pista': 'Metal', 'palabra_en': 'Handcuffs', 'pista_en': 'Metal'},
    {'palabra': 'Bondage', 'pista': 'Cuerdas', 'palabra_en': 'Bondage', 'pista_en': 'Ropes'},
    {'palabra': 'Stripper', 'pista': 'Baile', 'palabra_en': 'Stripper', 'pista_en': 'Dance'},
    {'palabra': 'Preservativo', 'pista': 'Goma', 'palabra_en': 'Condom', 'pista_en': 'Rubber'},
    {'palabra': 'Orgía', 'pista': 'Grupo', 'palabra_en': 'Orgy', 'pista_en': 'Group'},
    {'palabra': 'Tanga', 'pista': 'Pequeño', 'palabra_en': 'Thong', 'pista_en': 'Small'},
    {'palabra': 'Lubricante', 'pista': 'Gel', 'palabra_en': 'Lubricant', 'pista_en': 'Gel'},
    {'palabra': 'Poliamor', 'pista': 'Varios', 'palabra_en': 'Polyamory', 'pista_en': 'Several'},
    {'palabra': 'BDSM', 'pista': 'Siglas', 'palabra_en': 'BDSM', 'pista_en': 'Acronym'},
    {'palabra': 'Orgasm0', 'pista': 'Final', 'palabra_en': 'Orgasm', 'pista_en': 'End'},
    {'palabra': 'Swinger', 'pista': 'Intercambio', 'palabra_en': 'Swinger', 'pista_en': 'Exchange'},
    {'palabra': 'Fetichismo', 'pista': 'Gusto', 'palabra_en': 'Fetishism', 'pista_en': 'Taste'},
    {'palabra': 'Pornografía', 'pista': 'Vídeo', 'palabra_en': 'Pornography', 'pista_en': 'Video'},
    {'palabra': 'Látigo', 'pista': 'Cuero', 'palabra_en': 'Whip', 'pista_en': 'Leather'},
    {'palabra': 'Pezoneras', 'pista': 'Pecho', 'palabra_en': 'Pasties', 'pista_en': 'Chest'},
  ],
  'Terror': [
    {'palabra': 'Exorcista', 'pista': 'Niña', 'palabra_en': 'Exorcist', 'pista_en': 'Girl'},
    {'palabra': 'Sierra eléctrica', 'pista': 'Ruido', 'palabra_en': 'Chainsaw', 'pista_en': 'Noise'},
    {'palabra': 'Cementerio', 'pista': 'Tumbas', 'palabra_en': 'Cemetery', 'pista_en': 'Graves'},
    {'palabra': 'Fantasma', 'pista': 'Sábana', 'palabra_en': 'Ghost', 'pista_en': 'Sheet'},
    {'palabra': 'Drácula', 'pista': 'Colmillos', 'palabra_en': 'Dracula', 'pista_en': 'Fangs'},
    {'palabra': 'Zombi', 'pista': 'Cerebros', 'palabra_en': 'Zombie', 'pista_en': 'Brains'},
    {'palabra': 'Ouija', 'pista': 'Letras', 'palabra_en': 'Ouija', 'pista_en': 'Letters'},
    {'palabra': 'Payaso IT', 'pista': 'Globo', 'palabra_en': 'Pennywise', 'pista_en': 'Balloon'},
    {'palabra': 'Casa Encantada', 'pista': 'Puertas', 'palabra_en': 'Haunted House', 'pista_en': 'Doors'},
    {'palabra': 'Asesino', 'pista': 'Cuchillo', 'palabra_en': 'Killer', 'pista_en': 'Knife'},
    {'palabra': 'Pesadilla', 'pista': 'Sueño', 'palabra_en': 'Nightmare', 'pista_en': 'Dream'},
    {'palabra': 'Vampiro', 'pista': 'Sangre', 'palabra_en': 'Vampire', 'pista_en': 'Blood'},
    {'palabra': 'Hombre Lobo', 'pista': 'Luna', 'palabra_en': 'Werewolf', 'pista_en': 'Moon'},
    {'palabra': 'Esqueleto', 'pista': 'Huesos', 'palabra_en': 'Skeleton', 'pista_en': 'Bones'},
    {'palabra': 'Posesión', 'pista': 'Demonio', 'palabra_en': 'Possession', 'pista_en': 'Demon'},
    {'palabra': 'Momia', 'pista': 'Vendas', 'palabra_en': 'Mummy', 'pista_en': 'Bandages'},
    {'palabra': 'Muñeco Diabólico', 'pista': 'Chucky', 'palabra_en': 'Chucky', 'pista_en': 'Chucky'},
  ],
  'Cultura Friki': [
    {'palabra': 'Dragon Ball', 'pista': 'Bolas', 'palabra_en': 'Dragon Ball', 'pista_en': 'Balls'},
    {'palabra': 'Sable de luz', 'pista': 'Jedi', 'palabra_en': 'Lightsaber', 'pista_en': 'Jedi'},
    {'palabra': 'Cosplay', 'pista': 'Evento', 'palabra_en': 'Cosplay', 'pista_en': 'Event'},
    {'palabra': 'Marvel', 'pista': 'Cómic', 'palabra_en': 'Marvel', 'pista_en': 'Comic'},
    {'palabra': 'Naruto', 'pista': 'Zorro', 'palabra_en': 'Naruto', 'pista_en': 'Fox'},
    {'palabra': 'One Piece', 'pista': 'Sombrero', 'palabra_en': 'One Piece', 'pista_en': 'Hat'},
    {'palabra': 'Manga', 'pista': 'Papel', 'palabra_en': 'Manga', 'pista_en': 'Paper'},
    {'palabra': 'Dungeons & Dragons', 'pista': 'Dados', 'palabra_en': 'D&D', 'pista_en': 'Dice'},
    {'palabra': 'Anime', 'pista': 'Japón', 'palabra_en': 'Anime', 'pista_en': 'Japan'},
    {'palabra': 'Comic-Con', 'pista': 'San Diego', 'palabra_en': 'Comic-Con', 'pista_en': 'San Diego'},
    {'palabra': 'Goku', 'pista': 'Pelo', 'palabra_en': 'Goku', 'pista_en': 'Hair'},
    {'palabra': 'Pokédex', 'pista': 'Lista', 'palabra_en': 'Pokédex', 'pista_en': 'List'},
    {'palabra': 'Cthulhu', 'pista': 'Tentáculos', 'palabra_en': 'Cthulhu', 'pista_en': 'Tentacles'},
    {'palabra': 'Star Trek', 'pista': 'Nave', 'palabra_en': 'Star Trek', 'pista_en': 'Ship'},
    {'palabra': 'Lord of the Rings', 'pista': 'Anillo', 'palabra_en': 'Lord of the Rings', 'pista_en': 'Ring'},
  ],
  'Marcas Famosas': [
    {'palabra': 'Ferrari', 'pista': 'Rojo', 'palabra_en': 'Ferrari', 'pista_en': 'Red'},
    {'palabra': 'Coca-Cola', 'pista': 'Lata', 'palabra_en': 'Coca-Cola', 'pista_en': 'Can'},
    {'palabra': 'Apple', 'pista': 'iPhone', 'palabra_en': 'Apple', 'pista_en': 'iPhone'},
    {'palabra': 'Nike', 'pista': 'Zapatillas', 'palabra_en': 'Nike', 'pista_en': 'Sneakers'},
    {'palabra': 'Starbucks', 'pista': 'Vaso', 'palabra_en': 'Starbucks', 'pista_en': 'Cup'},
    {'palabra': 'McDonalds', 'pista': 'M', 'palabra_en': 'McDonalds', 'pista_en': 'M'},
    {'palabra': 'Amazon', 'pista': 'Paquete', 'palabra_en': 'Amazon', 'pista_en': 'Package'},
    {'palabra': 'Adidas', 'pista': 'Rayas', 'palabra_en': 'Adidas', 'pista_en': 'Stripes'},
    {'palabra': 'Google', 'pista': 'Buscador', 'palabra_en': 'Google', 'pista_en': 'Search engine'},
    {'palabra': 'Microsoft', 'pista': 'Windows', 'palabra_en': 'Microsoft', 'pista_en': 'Windows'},
    {'palabra': 'Disney', 'pista': 'Ratón', 'palabra_en': 'Disney', 'pista_en': 'Mouse'},
    {'palabra': 'Samsung', 'pista': 'Corea', 'palabra_en': 'Samsung', 'pista_en': 'Korea'},
    {'palabra': 'Pepsi', 'pista': 'Azul', 'palabra_en': 'Pepsi', 'pista_en': 'Blue'},
    {'palabra': 'Zara', 'pista': 'Ropa', 'palabra_en': 'Zara', 'pista_en': 'Clothes'},
    {'palabra': 'Ikea', 'pista': 'Muebles', 'palabra_en': 'Ikea', 'pista_en': 'Furniture'},
  ],
  'Países del Mundo': [
    {'palabra': 'Japón', 'pista': 'Asia', 'palabra_en': 'Japan', 'pista_en': 'Asia'},
    {'palabra': 'Brasil', 'pista': 'Fútbol', 'palabra_en': 'Brazil', 'pista_en': 'Soccer'},
    {'palabra': 'Egipto', 'pista': 'Desierto', 'palabra_en': 'Egypt', 'pista_en': 'Desert'},
    {'palabra': 'Australia', 'pista': 'Isla', 'palabra_en': 'Australia', 'pista_en': 'Island'},
    {'palabra': 'Rusia', 'pista': 'Frío', 'palabra_en': 'Russia', 'pista_en': 'Cold'},
    {'palabra': 'México', 'pista': 'Picante', 'palabra_en': 'Mexico', 'pista_en': 'Spicy'},
    {'palabra': 'Italia', 'pista': 'Botas', 'palabra_en': 'Italy', 'pista_en': 'Boots'},
    {'palabra': 'España', 'pista': 'Europa', 'palabra_en': 'Spain', 'pista_en': 'Europe'},
    {'palabra': 'China', 'pista': 'Muralla', 'palabra_en': 'China', 'pista_en': 'Wall'},
    {'palabra': 'Canadá', 'pista': 'Hoja', 'palabra_en': 'Canada', 'pista_en': 'Leaf'},
    {'palabra': 'Argentina', 'pista': 'Tango', 'palabra_en': 'Argentina', 'pista_en': 'Tango'},
    {'palabra': 'Francia', 'pista': 'Torre', 'palabra_en': 'France', 'pista_en': 'Tower'},
    {'palabra': 'India', 'pista': 'Vacas', 'palabra_en': 'India', 'pista_en': 'Cows'},
    {'palabra': 'Alemania', 'pista': 'Cerveza', 'palabra_en': 'Germany', 'pista_en': 'Beer'},
    {'palabra': 'Estados Unidos', 'pista': 'Bandera', 'palabra_en': 'United States', 'pista_en': 'Flag'},
  ],
  'Súper Lujo': [
    {'palabra': 'Diamante', 'pista': 'Brillo', 'palabra_en': 'Diamond', 'pista_en': 'Shine'},
    {'palabra': 'Yate', 'pista': 'Agua', 'palabra_en': 'Yacht', 'pista_en': 'Water'},
    {'palabra': 'Mansión', 'pista': 'Jardín', 'palabra_en': 'Mansion', 'pista_en': 'Garden'},
    {'palabra': 'Jet Privado', 'pista': 'Aire', 'palabra_en': 'Private Jet', 'pista_en': 'Air'},
    {'palabra': 'Rolex', 'pista': 'Hora', 'palabra_en': 'Rolex', 'pista_en': 'Time'},
    {'palabra': 'Caviar', 'pista': 'Caro', 'palabra_en': 'Caviar', 'pista_en': 'Expensive'},
    {'palabra': 'Limusina', 'pista': 'Largo', 'palabra_en': 'Limousine', 'pista_en': 'Long'},
    {'palabra': 'Champán', 'pista': 'Burbujas', 'palabra_en': 'Champagne', 'pista_en': 'Bubbles'},
    {'palabra': 'Mayordomo', 'pista': 'Servicio', 'palabra_en': 'Butler', 'pista_en': 'Service'},
    {'palabra': 'Isla Privada', 'pista': 'Aislado', 'palabra_en': 'Private Island', 'pista_en': 'Isolated'},
    {'palabra': 'Helicóptero', 'pista': 'Hélices', 'palabra_en': 'Helicopter', 'pista_en': 'Propellers'},
    {'palabra': 'Penthouse', 'pista': 'Ático', 'palabra_en': 'Penthouse', 'pista_en': 'Penthouse'},
    {'palabra': 'Oro', 'pista': 'Metal', 'palabra_en': 'Gold', 'pista_en': 'Metal'},
    {'palabra': 'Lamborghini', 'pista': 'Toro', 'palabra_en': 'Lamborghini', 'pista_en': 'Bull'},
    {'palabra': 'Guardaespaldas', 'pista': 'Traje', 'palabra_en': 'Bodyguard', 'pista_en': 'Suit'},
  ],
  'Música y Leyendas': [
    {'palabra': 'Freddie Mercury', 'pista': 'Queen', 'palabra_en': 'Freddie Mercury', 'pista_en': 'Queen'},
    {'palabra': 'Michael Jackson', 'pista': 'Baile', 'palabra_en': 'Michael Jackson', 'pista_en': 'Dance'},
    {'palabra': 'The Beatles', 'pista': 'Cuatro', 'palabra_en': 'The Beatles', 'pista_en': 'Four'},
    {'palabra': 'Guitarra Eléctrica', 'pista': 'Solo', 'palabra_en': 'Electric Guitar', 'pista_en': 'Solo'},
    {'palabra': 'Grammy', 'pista': 'Premio', 'palabra_en': 'Grammy', 'pista_en': 'Award'},
    {'palabra': 'Concierto', 'pista': 'Gente', 'palabra_en': 'Concert', 'pista_en': 'People'},
    {'palabra': 'Festival', 'pista': 'Verano', 'palabra_en': 'Festival', 'pista_en': 'Summer'},
    {'palabra': 'Rolling Stones', 'pista': 'Lengua', 'palabra_en': 'Rolling Stones', 'pista_en': 'Tongue'},
    {'palabra': 'Madonna', 'pista': 'Reina', 'palabra_en': 'Madonna', 'pista_en': 'Queen'},
    {'palabra': 'David Bowie', 'pista': 'Rayo', 'palabra_en': 'David Bowie', 'pista_en': 'Lightning'},
    {'palabra': 'Elvis Presley', 'pista': 'Tupé', 'palabra_en': 'Elvis Presley', 'pista_en': 'Quiff'},
    {'palabra': 'Bob Marley', 'pista': 'Pelo', 'palabra_en': 'Bob Marley', 'pista_en': 'Hair'},
    {'palabra': 'Nirvana', 'pista': 'Grunge', 'palabra_en': 'Nirvana', 'pista_en': 'Grunge'},
    {'palabra': 'Daft Punk', 'pista': 'Casco', 'palabra_en': 'Daft Punk', 'pista_en': 'Helmet'},
    {'palabra': 'Spotify', 'pista': 'Verde', 'palabra_en': 'Spotify', 'pista_en': 'Green'},
  ],
  'Superhéroes': [
    {'palabra': 'Iron Man', 'pista': 'Tony', 'palabra_en': 'Iron Man', 'pista_en': 'Tony'},
    {'palabra': 'Spider-Man', 'pista': 'Rojo', 'palabra_en': 'Spider-Man', 'pista_en': 'Red'},
    {'palabra': 'Kryptonita', 'pista': 'Piedra', 'palabra_en': 'Kryptonite', 'pista_en': 'Stone'},
    {'palabra': 'Batcueva', 'pista': 'Batman', 'palabra_en': 'Batcave', 'pista_en': 'Batman'},
    {'palabra': 'Thor', 'pista': 'Rayo', 'palabra_en': 'Thor', 'pista_en': 'Lightning'},
    {'palabra': 'Vengadores', 'pista': 'Equipo', 'palabra_en': 'Avengers', 'pista_en': 'Team'},
    {'palabra': 'Wonder Woman', 'pista': 'Lazo', 'palabra_en': 'Wonder Woman', 'pista_en': 'Lasso'},
    {'palabra': 'Hulk', 'pista': 'Verde', 'palabra_en': 'Hulk', 'pista_en': 'Green'},
    {'palabra': 'Flash', 'pista': 'Correr', 'palabra_en': 'Flash', 'pista_en': 'Run'},
    {'palabra': 'Superman', 'pista': 'Capa', 'palabra_en': 'Superman', 'pista_en': 'Cape'},
    {'palabra': 'Capitán América', 'pista': 'Escudo', 'palabra_en': 'Captain America', 'pista_en': 'Shield'},
    {'palabra': 'X-Men', 'pista': 'Mutantes', 'palabra_en': 'X-Men', 'pista_en': 'Mutants'},
    {'palabra': 'Black Widow', 'pista': 'Rusia', 'palabra_en': 'Black Widow', 'pista_en': 'Russia'},
    {'palabra': 'Pantera Negra', 'pista': 'África', 'palabra_en': 'Black Panther', 'pista_en': 'Africa'},
    {'palabra': 'Joker', 'pista': 'Risa', 'palabra_en': 'Joker', 'pista_en': 'Laugh'},
  ],
  'Años 80 y 90': [
    {'palabra': 'Walkman', 'pista': 'Cinta', 'palabra_en': 'Walkman', 'pista_en': 'Tape'},
    {'palabra': 'Cinta VHS', 'pista': 'Peli', 'palabra_en': 'VHS Tape', 'pista_en': 'Movie'},
    {'palabra': 'Tamagotchi', 'pista': 'Mascota', 'palabra_en': 'Tamagotchi', 'pista_en': 'Pet'},
    {'palabra': 'Game Boy', 'pista': 'Tetris', 'palabra_en': 'Game Boy', 'pista_en': 'Tetris'},
    {'palabra': 'Disquete', 'pista': 'Guardar', 'palabra_en': 'Floppy Disk', 'pista_en': 'Save'},
    {'palabra': 'Pac-Man', 'pista': 'Amarillo', 'palabra_en': 'Pac-Man', 'pista_en': 'Yellow'},
    {'palabra': 'Cubo de Rubik', 'pista': 'Colores', 'palabra_en': 'Rubik\'s Cube', 'pista_en': 'Colors'},
    {'palabra': 'Nokia 3310', 'pista': 'Duro', 'palabra_en': 'Nokia 3310', 'pista_en': 'Tough'},
    {'palabra': 'Jurassic Park', 'pista': 'Dinos', 'palabra_en': 'Jurassic Park', 'pista_en': 'Dinos'},
    {'palabra': 'Back to the Future', 'pista': 'Coche', 'palabra_en': 'Back to the Future', 'pista_en': 'Car'},
    {'palabra': 'Nirvana', 'pista': 'Música', 'palabra_en': 'Nirvana', 'pista_en': 'Music'},
    {'palabra': 'Spice Girls', 'pista': 'Grupo', 'palabra_en': 'Spice Girls', 'pista_en': 'Group'},
    {'palabra': 'Titanic', 'pista': 'Peli', 'palabra_en': 'Titanic', 'pista_en': 'Movie'},
    {'palabra': 'Messenger', 'pista': 'Chat', 'palabra_en': 'Messenger', 'pista_en': 'Chat'},
    {'palabra': 'MTV', 'pista': 'Música', 'palabra_en': 'MTV', 'pista_en': 'Music'},
  ],
};