// lib/datos.dart

final Map<String, List<Map<String, String>>> categorias = {
  'Animales': [
    {'palabra': 'Perro', 'pista': 'Mascota'},
    {'palabra': 'Gato', 'pista': 'Mascota'},
    {'palabra': 'Elefante', 'pista': 'Mamífero'},
    {'palabra': 'Delfín', 'pista': 'Inteligente'},
    {'palabra': 'León', 'pista': 'Depredador'},
    {'palabra': 'Tiburón', 'pista': 'Depredador'},
    {'palabra': 'Pingüino', 'pista': 'Antártida'},
    {'palabra': 'Serpiente', 'pista': 'Reptil'},
    {'palabra': 'Jirafa', 'pista': 'Altura'},
    {'palabra': 'Vaca', 'pista': 'Granja'},
  ],
  'Comidas': [
    {'palabra': 'Paella', 'pista': 'Arroz'},
    {'palabra': 'Tortilla', 'pista': 'Huevos'},
    {'palabra': 'Pizza', 'pista': 'Horno'},
    {'palabra': 'Hamburguesa', 'pista': 'Carne'},
    {'palabra': 'Croquetas', 'pista': 'Fritura'},
    {'palabra': 'Sushi', 'pista': 'Arroz'},
    {'palabra': 'Lentejas', 'pista': 'Legumbres'},
    {'palabra': 'Gazpacho', 'pista': 'Frío'},
    {'palabra': 'Pasta', 'pista': 'Harina'},
    {'palabra': 'Churros', 'pista': 'Desayuno'},
  ],
  'Objetos': [
    {'palabra': 'Móvil', 'pista': 'Tecnología'},
    {'palabra': 'Ordenador', 'pista': 'Tecnología'},
    {'palabra': 'Bicicleta', 'pista': 'Ruedas'},
    {'palabra': 'Gafas', 'pista': 'Cristal'},
    {'palabra': 'Reloj', 'pista': 'Tiempo'},
    {'palabra': 'Mochila', 'pista': 'Equipaje'},
    {'palabra': 'Cama', 'pista': 'Descanso'},
    {'palabra': 'Espejo', 'pista': 'Reflejo'},
    {'palabra': 'Paraguas', 'pista': 'Lluvia'},
    {'palabra': 'Coche', 'pista': 'Motor'},
  ],
  'Lugares': [
    {'palabra': 'Madrid', 'pista': 'Capital'},
    {'palabra': 'París', 'pista': 'Europa'},
    {'palabra': 'La Playa', 'pista': 'Naturaleza'},
    {'palabra': 'El Colegio', 'pista': 'Educación'},
    {'palabra': 'Nueva York', 'pista': 'Rascacielos'},
    {'palabra': 'Gimnasio', 'pista': 'Deporte'},
    {'palabra': 'Cine', 'pista': 'Ocio'},
    {'palabra': 'Hospital', 'pista': 'Salud'},
    {'palabra': 'Aeropuerto', 'pista': 'Viajes'},
    {'palabra': 'Supermercado', 'pista': 'Compras'},
  ],
  'Cine y TV': [
    {'palabra': 'Star Wars', 'pista': 'Espacio'},
    {'palabra': 'Harry Potter', 'pista': 'Magia'},
    {'palabra': 'Titanic', 'pista': 'Tragedia'},
    {'palabra': 'Los Simpson', 'pista': 'Animación'},
    {'palabra': 'La Casa de Papel', 'pista': 'Robo'},
    {'palabra': 'Batman', 'pista': 'Héroe'},
    {'palabra': 'Jurassic Park', 'pista': 'Dinosaurios'},
    {'palabra': 'Toy Story', 'pista': 'Infantil'},
    {'palabra': 'Avatar', 'pista': 'Ciencia Ficción'},
    {'palabra': 'El Rey León', 'pista': 'Infantil'},
  ],
  'Deportes': [
    {'palabra': 'Fútbol', 'pista': 'Balón'},
    {'palabra': 'Baloncesto', 'pista': 'Balón'},
    {'palabra': 'Tenis', 'pista': 'Raqueta'},
    {'palabra': 'Natación', 'pista': 'Agua'},
    {'palabra': 'Ciclismo', 'pista': 'Ruedas'},
    {'palabra': 'Boxeo', 'pista': 'Contacto'},
    {'palabra': 'Golf', 'pista': 'Palo'},
    {'palabra': 'Esquí', 'pista': 'Nieve'},
    {'palabra': 'Yoga', 'pista': 'Relajación'},
    {'palabra': 'Voleibol', 'pista': 'Red'},
  ],
  'Profesiones': [
    {'palabra': 'Médico', 'pista': 'Sanitario'},
    {'palabra': 'Bombero', 'pista': 'Emergencias'},
    {'palabra': 'Policía', 'pista': 'Uniforme'},
    {'palabra': 'Profesor', 'pista': 'Educación'},
    {'palabra': 'Astronauta', 'pista': 'Espacio'},
    {'palabra': 'Mecánico', 'pista': 'Taller'},
    {'palabra': 'Peluquero', 'pista': 'Estética'},
    {'palabra': 'Cocinero', 'pista': 'Hostelería'},
    {'palabra': 'Pintor', 'pista': 'Arte'},
    {'palabra': 'Cantante', 'pista': 'Escenario'},
  ],
  'Videojuegos': [
    {'palabra': 'Super Mario', 'pista': 'Plataformas'},
    {'palabra': 'Minecraft', 'pista': 'Construcción'},
    {'palabra': 'Fortnite', 'pista': 'Disparos'},
    {'palabra': 'FIFA', 'pista': 'Deporte'},
    {'palabra': 'Pokémon', 'pista': 'Colección'},
    {'palabra': 'Zelda', 'pista': 'Aventura'},
    {'palabra': 'Tetris', 'pista': 'Puzle'},
    {'palabra': 'Among Us', 'pista': 'Nave'},
    {'palabra': 'Pac-Man', 'pista': 'Retro'},
    {'palabra': 'GTA', 'pista': 'Mundo Abierto'},
  ],
  'Personajes Famosos': [
    {'palabra': 'Rafa Nadal', 'pista': 'Deportista'},
    {'palabra': 'Messi', 'pista': 'Deportista'},
    {'palabra': 'Rosalía', 'pista': 'Música'},
    {'palabra': 'Ibai Llanos', 'pista': 'Internet'},
    {'palabra': 'Spider-Man', 'pista': 'Ficción'},
    {'palabra': 'Mickey Mouse', 'pista': 'Dibujo'},
    {'palabra': 'Sherlock Holmes', 'pista': 'Ficción'},
    {'palabra': 'Don Quijote', 'pista': 'Literatura'},
    {'palabra': 'Cristiano Ronaldo', 'pista': 'Deportista'},
    {'palabra': 'Donald Trump', 'pista': 'Política'},
  ],
  'Cosas de Casa': [
    {'palabra': 'Frigorífico', 'pista': 'Electrodoméstico'},
    {'palabra': 'Microondas', 'pista': 'Electrodoméstico'},
    {'palabra': 'Lavadora', 'pista': 'Limpieza'},
    {'palabra': 'Sofá', 'pista': 'Salón'},
    {'palabra': 'Televisión', 'pista': 'Pantalla'},
    {'palabra': 'Ducha', 'pista': 'Baño'},
    {'palabra': 'Cama', 'pista': 'Dormitorio'},
    {'palabra': 'Escoba', 'pista': 'Limpieza'},
    {'palabra': 'Lámpara', 'pista': 'Iluminación'},
    {'palabra': 'Espejo', 'pista': 'Cristal'},
  ],
  'Adultos': [
    {'palabra': 'Vibrador', 'pista': 'Objeto de placer'},
    {'palabra': 'Lencería', 'pista': 'Ropa interior sexy'},
    {'palabra': 'Kamasutra', 'pista': 'Libro de posturas'},
    {'palabra': 'Esposas', 'pista': 'Se usan para arrestar... o jugar'},
    {'palabra': 'Bondage', 'pista': 'Práctica con cuerdas'},
    {'palabra': 'Stripper', 'pista': 'Baila en una barra'},
    {'palabra': 'Preservativo', 'pista': 'Funda de látex'},
    {'palabra': 'Orgía', 'pista': 'Fiesta de mucha gente'},
    {'palabra': 'Tanga', 'pista': 'Ropa interior mínima'},
  ],
  'Terror': [
    {'palabra': 'Exorcista', 'pista': 'Una película muy famosa'},
    {'palabra': 'Sierra eléctrica', 'pista': 'Arma de asesino'},
    {'palabra': 'Cementerio', 'pista': 'Lugar de descanso'},
    {'palabra': 'Fantasma', 'pista': 'Ser del más allá'},
    {'palabra': 'Drácula', 'pista': 'Chupasangre'},
    {'palabra': 'Zombi', 'pista': 'Caminante muerto'},
    {'palabra': 'Ouija', 'pista': 'Tablero espiritual'},
  ],
  'Cultura Friki': [
    {'palabra': 'Dragon Ball', 'pista': 'Serie de anime'},
    {'palabra': 'Sable de luz', 'pista': 'Arma de Star Wars'},
    {'palabra': 'Cosplay', 'pista': 'Disfrazarse de personaje'},
    {'palabra': 'Marvel', 'pista': 'Universo de héroes'},
    {'palabra': 'Naruto', 'pista': 'Ninja naranja'},
    {'palabra': 'One Piece', 'pista': 'Piratas'},
    {'palabra': 'Manga', 'pista': 'Cómic japonés'},
  ],
  'Marcas Famosas': [
    {'palabra': 'Ferrari', 'pista': 'Coche de lujo'},
    {'palabra': 'Coca-Cola', 'pista': 'Bebida refrescante'},
    {'palabra': 'Apple', 'pista': 'Tecnología de la manzana'},
    {'palabra': 'Nike', 'pista': 'Ropa deportiva'},
    {'palabra': 'Starbucks', 'pista': 'Cafetería'},
    {'palabra': 'McDonalds', 'pista': 'Hamburguesas'},
    {'palabra': 'Amazon', 'pista': 'Compras online'},
  ],
  'Países del Mundo': [
    {'palabra': 'Japón', 'pista': 'País del sol naciente'},
    {'palabra': 'Brasil', 'pista': 'Sudamérica'},
    {'palabra': 'Egipto', 'pista': 'Pirámides'},
    {'palabra': 'Australia', 'pista': 'Canguros'},
    {'palabra': 'Rusia', 'pista': 'País muy grande'},
    {'palabra': 'México', 'pista': 'Tacos y tequila'},
    {'palabra': 'Italia', 'pista': 'Pizza y pasta'},
  ],
  'Súper Lujo': [
    {'palabra': 'Diamante', 'pista': 'Piedra preciosa'},
    {'palabra': 'Yate', 'pista': 'Barco de ricos'},
    {'palabra': 'Mansión', 'pista': 'Casa gigante'},
    {'palabra': 'Jet Privado', 'pista': 'Avión personal'},
    {'palabra': 'Rolex', 'pista': 'Reloj caro'},
    {'palabra': 'Caviar', 'pista': 'Huevas de pescado'},
    {'palabra': 'Limusina', 'pista': 'Coche muy largo'},
  ],
  'Música y Leyendas': [
    {'palabra': 'Freddie Mercury', 'pista': 'Cantante de Queen'},
    {'palabra': 'Michael Jackson', 'pista': 'Rey del pop'},
    {'palabra': 'The Beatles', 'pista': 'Grupo de Liverpool'},
    {'palabra': 'Guitarra Eléctrica', 'pista': 'Instrumento de Rock'},
    {'palabra': 'Grammy', 'pista': 'Premio musical'},
    {'palabra': 'Concierto', 'pista': 'Música en directo'},
    {'palabra': 'Festival', 'pista': 'Muchos conciertos'},
  ],
  'Superhéroes': [
    {'palabra': 'Iron Man', 'pista': 'Armadura roja'},
    {'palabra': 'Spider-Man', 'pista': 'Telarañas'},
    {'palabra': 'Kryptonita', 'pista': 'Debilidad de héroe'},
    {'palabra': 'Batcueva', 'pista': 'Escondite secreto'},
    {'palabra': 'Thor', 'pista': 'Martillo mágico'},
    {'palabra': 'Vengadores', 'pista': 'Grupo de héroes'},
    {'palabra': 'Wonder Woman', 'pista': 'Heroína'},
  ],
  'Años 80 y 90': [
    {'palabra': 'Walkman', 'pista': 'Para escuchar música'},
    {'palabra': 'Cinta VHS', 'pista': 'Para ver pelis'},
    {'palabra': 'Tamagotchi', 'pista': 'Mascota virtual'},
    {'palabra': 'Game Boy', 'pista': 'Consola portátil'},
    {'palabra': 'Disquete', 'pista': 'Para guardar archivos'},
    {'palabra': 'Pac-Man', 'pista': 'Comecocos'},
    {'palabra': 'Cubo de Rubik', 'pista': 'Puzle de colores'},
  ],
};